name: tf-fmt
on: 
  push: 
  pull_request:
    branches: [master]
jobs:
  tf-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.1
      - run: terraform fmt -recursive -check